spring:
  application:
    name: zuhee-gw-api
  datasource:
    url: jdbc:postgresql://localhost:5432/zuhee_gw
    username: zuhee
    password: password123!
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui/index.html

logging:
  level:
    com.zuhee.gw: debug
